name: AFL++ Fuzz DuckDB File Readers
on:
  schedule:
    - cron: "42 23 * * *"
  workflow_dispatch:

jobs:
  run-file-reader-fuzzer:
    name: Run AFL++ File Reader Fuzzer
    uses: duckdblabs/duckdb-aflplusplus/.github/workflows/FileReaderFuzzer.yml@main
    with:
      csv: true
      json: true
      parquet: true
      duckdbRepo: duckdb/duckdb
      duckdb_ref: main
      fuzzTime: 14400
    secrets:
      FUZZEROFDUCKSKEY: ${{ secrets.FUZZEROFDUCKSKEY }}
